/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes version 20210604 of the Zora Metadata Standard
 */
export interface Zora20210604 {
  /**
   * The description of the media
   */
  description: string;
  /**
   * The mimeType of the media
   */
  mimeType: string;
  /**
   * This property is the name of the Media
   */
  name: string;
  /**
   * This property defines the calendar version of the schema so that consumers can correctly parse the json
   */
  version: string;
  /**
   * This property defines an optional preview image URL for the media
   */
  image?: string;
  /**
   * This property defines an optional external URL that can reference a webpage or external asset for the NFT
   */
  external_url?: string;
  /**
   * A URL to a multi-media attachment for the item. The file extensions GLTF, GLB, WEBM, MP4, M4V, OGV, and OGG are supported, along with the audio-only extensions MP3, WAV, and OGA. Animation_url also supports HTML pages, allowing you to build rich experiences using JavaScript canvas, WebGL, and more. Access to browser extensions is not supported
   */
  animation_url?: string;
  /**
   * This property defines any additional attributes for the item
   */
  attributes?: Attribute[];
}
export interface Attribute {
  /**
   * The name of the trait
   */
  trait_type: string;
  /**
   * The value of the trait
   */
  value: string | number | boolean;
  /**
   * A field indicating how the `value` data should be displayed. Defaults to 'string'
   */
  display_type?: string;
  [k: string]: unknown;
}
