/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes version 20210101 of the Zora Metadata Standard
 */
export interface Zora20210101 {
  /**
   * The description of the media
   */
  description: string;
  /**
   * The mimeType of the media
   */
  mimeType: string;
  /**
   * This property is the name of the Media
   */
  name: string;
  /**
   * This property defines the calendar version of the schema so that consumers can correctly parse the json
   */
  version: string;
}
