/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes version 20210221 of the metadata standard for the amulet poem format, designed for the Zora protocol.
 */
export interface Amulet20210221 {
  /**
   * The description of the amulet, which should include at minimum (1) a link to the current formal definition and (2) a link to the carbon offset purchased in the poem's name.
   */
  description: string;
  /**
   * The mimeType of the amulet. This will always be text/plain.
   */
  mimeType: string;
  /**
   * The title of the amulet.
   */
  name: string;
  /**
   * The text of the amulet. You should include this if possible, but it's not formally required. The text at the contentURI in the Zora NFT is considered the canonical version.
   */
  poem?: string;
  /**
   * The rarity level of the amulet.
   */
  rarity: "common" | "uncommon" | "rare" | "epic" | "legencary" | "mythic" | "beyond mythic";
  /**
   * The calendar version of the schema.
   */
  version: string;
}
